openapi: 3.0.0
info:
  title: Fitness API
  version: 1.0.0
  description: API для керування користувачами, тренуваннями, вправами та нагадуваннями

servers:
  - url: https://localhost:8080

tags:
  - name: Authentication
    description: Авторизація та автентифікація
  - name: Users
    description: Керування користувачами
  - name: Workouts
    description: Тренування користувачів
  - name: Exercises
    description: Вправи для тренувань
  - name: Workout Exercises
    description: Прив'язка вправ до тренування
  - name: Reminders
    description: Нагадування користувачів
  - name: Progress
    description: Аналітика прогресу

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email
      required: [id, name, email]

    UserInput:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
      required: [name, email, password]

    Workout:
      type: object
      properties:
        id:
          type: string
          format: uuid
        date:
          type: string
          format: date
        name:
          type: string
        type:
          type: string
          enum: [фулбаді, верх-низ, спліт]
        note:
          type: string
        user_id:
          type: string
          format: uuid
        exercises:
          type: array
          items:
            $ref: '#/components/schemas/WorkoutExerciseInput'
      required: [id, date, name, type, user_id]

    WorkoutInput:
      type: object
      properties:
        date:
          type: string
          format: date
        name:
          type: string
        type:
          type: string
          enum: [фулбаді, верх-низ, спліт]
        note:
          type: string
        user_id:
          type: string
          format: uuid
        exercises:
          type: array
          items:
            $ref: '#/components/schemas/WorkoutExerciseInput'
      required: [date, name, type, user_id]

    Exercise:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        type:
          type: string
        muscle_group:
          type: string
      required: [id, name]

    ExerciseInput:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        muscle_group:
          type: string
      required: [name]

    WorkoutExercise:
      type: object
      properties:
        id:
          type: string
          format: uuid
        reps:
          type: integer
        weight:
          type: number
          format: float
        sets:
          type: integer
        note:
          type: string
        exercise_id:
          type: string
          format: uuid
        workout_id:
          type: string
          format: uuid
      required: [id, reps, sets, exercise_id, workout_id]

    WorkoutExerciseInput:
      type: object
      properties:
        reps:
          type: integer
        weight:
          type: number
          format: float
        sets:
          type: integer
        note:
          type: string
        exercise_id:
          type: string
          format: uuid
        workout_id:
          type: string
          format: uuid
      required: [reps, sets, exercise_id, workout_id]

    Reminder:
      type: object
      properties:
        id:
          type: string
          format: uuid
        time:
          type: string
          format: date-time
        message:
          type: string
        user_id:
          type: string
          format: uuid
      required: [id, time, user_id]

    ReminderInput:
      type: object
      properties:
        time:
          type: string
          format: date-time
        message:
          type: string
        user_id:
          type: string
          format: uuid
      required: [time, user_id]

paths:
  /api/login:
    post:
      tags: [Authentication]
      summary: Авторизація користувача
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Успішна авторизація
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

  /api/signup:
    post:
      tags: [Users]
      summary: Реєстрація нового користувача
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: Користувач створений

  /api/users:
    get:
      tags: [Users]
      summary: Отримати список користувачів
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Успішно
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /api/workouts:
    get:
      tags: [Workouts]
      summary: Отримати список тренувань
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Список тренувань
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workout'

    post:
      tags: [Workouts]
      summary: Створити тренування з вправами
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkoutInput'
      responses:
        '201':
          description: Тренування з вправами створено

  /api/exercises:
    get:
      tags: [Exercises]
      summary: Отримати список вправ
      responses:
        '200':
          description: Список вправ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'

    post:
      tags: [Exercises]
      summary: Додати нову вправу
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExerciseInput'
      responses:
        '201':
          description: Вправу додано

  /api/workout-exercises:
    post:
      tags: [Workout Exercises]
      summary: Додати вправу до тренування
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkoutExerciseInput'
      responses:
        '201':
          description: Вправу додано до тренування

  /api/reminders:
    get:
      tags: [Reminders]
      summary: Отримати список нагадувань
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Список нагадувань
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reminder'

    post:
      tags: [Reminders]
      summary: Створити нагадування
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReminderInput'
      responses:
        '201':
          description: Нагадування створено

  /api/progress/summary:
    get:
      tags: [Progress]
      summary: Зведена статистика прогресу користувача
      parameters:
        - in: query
          name: range
          required: true
          schema:
            type: string
            enum: [week, month]
        - in: query
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Зведені дані
          content:
            application/json:
              schema:
                type: object
                properties:
                  days:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          format: date
                        volume:
                          type: number
                        sessions:
                          type: integer
                        est1rm_best:
                          type: number
                  totals:
                    type: object
                    properties:
                      volume:
                        type: number
                      sessions:
                        type: integer
                  trend:
                    type: object
                    properties:
                      est1rm_change_pct:
                        type: number
                      volume_change_pct:
                        type: number
                  stagnation:
                    type: boolean

  /api/progress/exercise:
    get:
      tags: [Progress]
      summary: Прогрес по конкретній вправі
      parameters:
        - in: query
          name: exerciseId
          required: true
          schema:
            type: string
            format: uuid
        - in: query
          name: range
          required: true
          schema:
            type: string
            enum: [week, month]
        - in: query
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Дані по вправі
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      format: date
                    est1rm_best:
                      type: number
                    volume:
                      type: number

  /api/sessions:
    get:
      tags: [Progress]
      summary: Історія тренувань користувача
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: string
            format: uuid
        - in: query
          name: cursor
          schema:
            type: string
            format: date
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        '200':
          description: Список тренувань
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    date:
                      type: string
                      format: date
                    name:
                      type: string
                    note:
                      type: string
